language: rust
sudo: false

cache: cargo

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # minimum rustc version
    - rust: 1.20.0
      script: cargo build

script:
  - cargo test

notifications:
  email:
    on_success: never
